name: bankplugin
main: bankplugin\Main
version: 1.0
api:
 - 3.0.0
 - 3.0.1
 - 3.0.0-ALPHA5
 - 3.0.0-ALPHA6
 - 3.0.0-ALPHA7
 - 3.0.0-ALPHA8
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10
load: POSTWORLD
author: gamesukimanIRS
description: Economyのドルと経験値をあずけられるプラグイン
commands:
  bank:
    description: "説明"
    usage: "/bank <money|exp> <a|r|g> <amount>"