--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/gamesukimanIRS/BankPluginAPI
branches:
- master
projects:
  bankpluginv1-1:
    path: bankplugin-v1_0_0-v1-1/
  bankpluginv1-2:
    path: bankplugin-v1_0_0-v1-2/
  bankpluginNewApiv2-1:
    path: bankplugin-v1_0_0-v2(NewApi)-1/
  bankpluginNewApiv2-2:
    path: bankplugin-v1_0_0-v2(NewApi)-2/
...
